version: "3"

services:
  app-server:
    container_name: server_jira
    build:
      context: .
      dockerfile: Dockerfile
    image: jira-app
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/jira
      DATASOURCE_USERNAME: jira
      DATASOURCE_PASSWORD: JiraRush
    depends_on:
      - postgres
    networks:
      - jirarush-network

  postgres:
    container_name: db_jira
    image: postgres
    expose:
      - "5432:5432"
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      POSTGRES_DB: jira
    networks:
      - jirarush-network

  nginx:
    container_name: nginx_jira
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-server
    networks:
      - jirarush-network

networks:
  jirarush-network:
    driver: bridge