#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8080
  test-mail: jira4jr@gmail.com
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  jpa:
    show-sql: true
    open-in-view: false

    # validate db by model
    hibernate:
      ddl-auto: validate

    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: ${UUSERNAME}
    password: ${PPASSWORD}

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  # Jackson Fields Serialization
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
            scope: ${OAUTH2_GITHUB_SCOPE}
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope: ${OAUTH2_GOOGLE_SCOPE}
          gitlab:
            client-id: ${OAUTH2_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH2_GITLAB_CLIENT_SECRET}
            client-name: ${OAUTH2_GITLAB_CLIENT_NAME}
            redirect-uri: ${OAUTH2_GITLAB_REDIRECT_URI}
            authorization-grant-type: ${OAUTH2_GITLAB_AUTHORIZATION_GRANT_TYPE}
            scope: ${OAUTH2_GITLAB_SCOPE}
        provider:
          gitlab:
            authorization-uri: ${OAUTH2_PROVIDER_GITLAB_AUTHORIZATION_URI}
            token-uri: ${OAUTH2_PROVIDER_GITLAB_TOKEN_URI}
            user-info-uri: ${OAUTH2_PROVIDER_GITLAB_USER_INFO_URI}
            user-name-attribute: ${OAUTH2_PROVIDER_GITLAB_USER_NAME_ATTRIBUTE}

  sql:
    init:
      mode: always

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: ${MAIL_SMTP}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
  thymeleaf.check-template-location: false

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  #  https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true
springdoc.swagger-ui.path: /doc