#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
app:
  host-url: http://localhost:8080
  test-mail: jira4jr@gmail.com
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    open-in-view: false
    # validate db by model
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  client:
    registration:
      github:
        client-id: ${GITHUB_CLIENT_ID}
        client-secret: ${GITHUB_CLIENT_SECRET}
        scope:
          - email
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        scope:
          - email
          - profile
      gitlab:
        client-id: ${GITLAB_CLIENT_ID}
        client-secret: ${GITLAB_CLIENT_SECRET}
        client-name: ${GITLAB_CLIENT_NAME}
        redirect-uri: ${GITLAB_REDIRECT_URI}
        authorization-grant-type: authorization_code
        scope: read_user
    provider:


  starttls:
    enable: true
  auth: true
  host: ${MAIL_HOST}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  thymeleaf.check-template-location: false

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
server:
  #  https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc.swagger-ui.path: /doc